### ISSUE TITLE
The link given in the repo description seems to be broken

### ISSUE THREAD

**Issue by vaibhav-kaushal** [openresty/lua-redis-parser#16]
The link wiki.nginx.org/luaredisparser leads to a seemingly empty site. This is how the site looks right now: 

<img width="1095" alt="Screenshot 2020-09-13 at 5 27 36 PM" src="https://user-images.githubusercontent.com/2824682/93017458-96d44b80-f5e6-11ea-82b8-2f4c79e8f4a9.png">

**Comment by agentzh** [comment]
Thanks for the catch. I've removed the link.
